### ISSUE TITLE
fix alignment p 27 in https://amp.acdh.oeaw.ac.at/amp-transcript__0028.html

### ISSUE THREAD

**Issue by timofruehwirth** [Auden-Musulin-Papers/amp-app#33]
dear @linxOD , in p 27 of https://amp.acdh.oeaw.ac.at/amp-transcript__0028.html the alignment of the transcribed text differs from the other pages ... can you pls help?

**Comment by linxOD** [comment]
dear @timofruehwirth this is due to the manual text insertions/removal without reconsidering linebreaks. If you switch off the image you will see that in this text areas the line is much longer then others. Due to reserved space of the image the linebreak happens when there is not enough space left (in case three is no linebreak before that happens). 

I guess we need to come up with a solution in how to handle this text insertions.

**Comment by linxOD** [comment]
Such manuel notes of the author to move text from one area to another ca also be encoded in TEI. I will look for examples.

**Comment by timofruehwirth** [comment]
Dear @linxOD : thanks for letting me know, I should have noticed that. Marking up additions and other textual revisions in TEI is on my long list titled "v0.2" :-)

**Comment by timofruehwirth** [comment]
I'll add this specific problem to the list and close the issue.

**Comment by linxOD** [comment]
where text should be added/moved:
<mod type="add" hand="#typed">
 <anchor xml:id="subst1"/>
</mod>

where text should be deleted/moved:
<mod type="move" rendition="#circle">
 <ptr target="#subst1"/>
 <del>which is neither liver nor cheese</del>
</mod>

**Comment by linxOD** [comment]
however, this is just an idea. Maybe there are better solutions. But in general the "mod" element is used to descrive modifications.

**Comment by timofruehwirth** [comment]
thank you, I also add this to the list

**Comment by linxOD** [comment]
Here is a powerpoint where I got this idea: http://gams.uni-graz.at/o:dhoxss2016-tei-transcription
